//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPath.HelloActivity.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPath.HelloActivity.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string Debug_Category {
            get {
                return ResourceManager.GetString("Debug_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If specified a debug log will be produced in the specified file..
        /// </summary>
        public static string DebugLog_Description {
            get {
                return ResourceManager.GetString("DebugLog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Log.
        /// </summary>
        public static string DebugLog_DisplayName {
            get {
                return ResourceManager.GetString("DebugLog_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputOutput.
        /// </summary>
        public static string InputOutput_Category {
            get {
                return ResourceManager.GetString("InputOutput_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope Activity.
        /// </summary>
        public static string ScopeActivity_Description {
            get {
                return ResourceManager.GetString("ScopeActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A scoped activity..
        /// </summary>
        public static string ScopeActivity_DisplayName {
            get {
                return ResourceManager.GetString("ScopeActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represent an object passed in by the outer scope..
        /// </summary>
        public static string ScopeActivity_ScopeId_Description {
            get {
                return ResourceManager.GetString("ScopeActivity_ScopeId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope Id.
        /// </summary>
        public static string ScopeActivity_ScopeId_DisplayName {
            get {
                return ResourceManager.GetString("ScopeActivity_ScopeId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select any data type..
        /// </summary>
        public static string TestActivity_DataType_Description {
            get {
                return ResourceManager.GetString("TestActivity_DataType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        public static string TestActivity_DataType_DisplayName {
            get {
                return ResourceManager.GetString("TestActivity_DataType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple test activity..
        /// </summary>
        public static string TestActivity_Description {
            get {
                return ResourceManager.GetString("TestActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Activity.
        /// </summary>
        public static string TestActivity_DisplayName {
            get {
                return ResourceManager.GetString("TestActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select any file..
        /// </summary>
        public static string TestActivity_FilePath_Description {
            get {
                return ResourceManager.GetString("TestActivity_FilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        public static string TestActivity_FilePath_DisplayName {
            get {
                return ResourceManager.GetString("TestActivity_FilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A flag to flip the other direction..
        /// </summary>
        public static string TestActivity_FlagFlip_Description {
            get {
                return ResourceManager.GetString("TestActivity_FlagFlip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag Flip.
        /// </summary>
        public static string TestActivity_FlagFlip_DisplayName {
            get {
                return ResourceManager.GetString("TestActivity_FlagFlip_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to a folder..
        /// </summary>
        public static string TestActivity_FolderPath_Description {
            get {
                return ResourceManager.GetString("TestActivity_FolderPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Path.
        /// </summary>
        public static string TestActivity_FolderPath_DisplayName {
            get {
                return ResourceManager.GetString("TestActivity_FolderPath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a file path is specified debug logs will be written to the specified file..
        /// </summary>
        public static string TestActivity_LogFile_Description {
            get {
                return ResourceManager.GetString("TestActivity_LogFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log File.
        /// </summary>
        public static string TestActivity_LogFile_DisplayName {
            get {
                return ResourceManager.GetString("TestActivity_LogFile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A personalized message the system returns..
        /// </summary>
        public static string TestActivity_Message_Description {
            get {
                return ResourceManager.GetString("TestActivity_Message_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string TestActivity_Message_DisplayName {
            get {
                return ResourceManager.GetString("TestActivity_Message_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select any pronoun..
        /// </summary>
        public static string TestActivity_RelativePronoun_Description {
            get {
                return ResourceManager.GetString("TestActivity_RelativePronoun_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative Pronoun.
        /// </summary>
        public static string TestActivity_RelativePronoun_DisplayName {
            get {
                return ResourceManager.GetString("TestActivity_RelativePronoun_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular text input..
        /// </summary>
        public static string TestActivity_TextInput_Description {
            get {
                return ResourceManager.GetString("TestActivity_TextInput_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Input.
        /// </summary>
        public static string TestActivity_TextInput_DisplayName {
            get {
                return ResourceManager.GetString("TestActivity_TextInput_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or enter your name..
        /// </summary>
        public static string TestActivity_YourName_Description {
            get {
                return ResourceManager.GetString("TestActivity_YourName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string TestActivity_YourName_DisplayName {
            get {
                return ResourceManager.GetString("TestActivity_YourName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple scope..
        /// </summary>
        public static string TestScope_Description {
            get {
                return ResourceManager.GetString("TestScope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Scope.
        /// </summary>
        public static string TestScope_DisplayName {
            get {
                return ResourceManager.GetString("TestScope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another string..
        /// </summary>
        public static string TestScope_OtherString_Description {
            get {
                return ResourceManager.GetString("TestScope_OtherString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other String.
        /// </summary>
        public static string TestScope_OtherString_DisplayName {
            get {
                return ResourceManager.GetString("TestScope_OtherString_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple string..
        /// </summary>
        public static string TestScope_TestString_Description {
            get {
                return ResourceManager.GetString("TestScope_TestString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test String.
        /// </summary>
        public static string TestScope_TestString_DisplayName {
            get {
                return ResourceManager.GetString("TestScope_TestString_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
